name: Dispatch workflows

on:
  push:
    branches:
      - ghatest

jobs:
  dispatch-dc:
    name: Dispatch DC workflow
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'libs/**'    
      - if: steps.changes.outputs.src == 'true'
        name: Trigger DC Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DC_PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'adobecom',
              repo: 'dc',
              workflow_id: 'test-milo.yml',
              ref: 'ghatest',
            }) 
